version: '3.9'
services:
  backend:
    restart: always
    container_name: 'kpd-backend'
    build: 
      context: backend
      dockerfile: Dockerfile
    image: kpd-backend
    ports:
      - 4000:3000
    env_file: 
      - .env
    depends_on:
      - postgres
    networks:
      - backend

  frontend:
    container_name: 'kpd-frontend'
    build: 
      context: frontend
      dockerfile: Dockerfile
    image: kpd-frontend
    ports:
      - 5000:80
    networks:
      - frontend
    
  postgres:
    restart: always
    container_name: 'kpd-postgres'
    image: postgres
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    env_file: 
      - .env
    networks:
      - backend

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports: 
      - '8081:8080'

networks:
  frontend:
  backend: